[tool.poetry]
name = "walletrestapi"
version = "0.1.0"
description = ""
authors = ["NazKar@Nazir <karimov.nazir00@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
isort = "^7.0.0"
black = "^26.1.0"
flake8 = "^7.3.0"
fastapi = "^0.128.0"
uvicorn = "^0.40.0"
sqlalchemy = "^2.0.45"
asyncpg = "^0.31.0"
psycopg2-binary = "^2.9.11"
alembic = "^1.18.1"
python-dotenv = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
